frontend:
  replicaCount: 1

  image:
    repository: kisho57/todo-frontend
    tag: 81818f2b00613629909cb3c30a14af184c459de8

  service:
    type: NodePort
    port: 5173
    nodePort: 30080

backend:
  replicaCount: 1

  image:
    repository: kisho57/todo-backend
    tag: 81818f2b00613629909cb3c30a14af184c459de8

  service:
    type: ClusterIP
    port: 3001

mongodb:
  replicaCount: 1

  image:
    repository: mongo
    tag: latest

  service:
    port: 27017

persistence:
  storage: 1Gi

config:
  mongoUri: mongodb://mongodb:27017/ToDo